title: ResourceRedConfig and urlConfig Detection 88426540
description: |
    Detect phishing sites that use ResourceRedConfig.js and urlConfig.json
references:
  - https://urlscan.io/result/88426540-8f66-4fe2-b8f2-526e7025ace7
  - https://urlscan.io/result/05189f5c-f969-45da-a6fd-d3fec490f0f7
  - https://urlscan.io/result/d4886a4c-114a-4a0a-9b07-614fddc6171f

detection:

    ResourceRedConfig:
        requests|contains: 'ResourceRedConfig.js'

    urlConfig:
        requests|contains: 'urlConfig.json'

    condition: ResourceRedConfig and urlConfig

tags:
  - kit
